package Exception;

public class Demo {
	public static void main(String[]args) {
//		int a=10;
//		int b=0;
//		try {
//		System.out.println(a/b);                                   //Arthimetic Exception;
//		}
//		catch (ArithmeticException e) {
//			System.out.println(e);
//			System.out.println("this is invalid data");
//		}
		
//		String a=null;
//		System.out.println("Hello World");
//		try {
//		String b=a.toUpperCase();
//		System.out.println(b);                    //Null Pointer Exception;
//		}
//		catch(NullPointerException e) {
//			System.out.println(e);
//		}
//		System.out.println("hi");
		
//		String a="7G";
//		System.out.println("Hai");           
//		try {
//		int b=Integer.parseInt(a);                //NumberFormat Exception;
//		                                            //String to integer;
//		System.out.println(b);
//		}
//		catch(NumberFormatException c) {
//			System.out.println(c);
//		}
		
//		String a="Sekar";
//		char b=a.charAt(0);
//		try  {
//		char c=a.charAt(5);
//		System.out.println(c);                          //String Index Out of bounds;
//		}
//		catch(StringIndexOutOfBoundsException e) {
//			System.out.println(e);
//		}
//		finally {
//			System.out.println("Invalid");
//		}
		
//		try {
//		int[] num= {99,79,86};
//		System.out.println(num[5]);
//		}
//		catch(ArrayIndexOutOfBoundsException a) {
//			System.out.println(a);
//		}
		
		String abb="Sekar";
		System.out.println(abb.indexOf("x"));
	}
}
